export {default as Layout} from "./Layout.jsx";
export {default as Hero} from "./HeroSection.jsx";
export {default as About} from "./About.jsx";
export {default as Education} from "./Education.jsx";
export {default as Experience} from "./Experience.jsx";
export {default as Projects} from "./Projects.jsx";
export {default as Contact} from "./Contact.jsx";
export {default as Resume} from "./Resume.jsx";
export {default as Seo} from "./Seo.jsx";